import {
  FaCode,
  FaTerminal,
  FaLaptopCode,
  FaGithub,
  FaGitAlt,
  FaGitlab,
  FaJs,
  FaPython,
  FaJava,
  FaHtml5,
  FaCss3Alt,
  FaReact,
  FaNodeJs,
  FaFacebook,
  FaTwitter,
  FaInstagram,
  FaLinkedin,
  FaYoutube,
  FaReddit,
  FaWhatsapp,
  FaTelegram,
  FaDiscord,
  FaTiktok,
  FaMapMarkerAlt,
  FaLocationArrow,
  FaMap,
  FaMapPin,
  FaGlobe,
  FaStreetView,
  FaCompass,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaArrowDown,
  FaHome,
  FaBars,
  FaTimes,
  FaChevronLeft,
  FaChevronRight,
  FaPhone,
  FaPhoneAlt,
  FaEnvelope,
  FaSms,
  FaCommentDots,
  FaMailBulk,
  FaFile,
  FaFileAlt,
  FaFilePdf,
  FaFileImage,
  FaFileVideo,
  FaFolder,
  FaDownload,
  FaUpload,
  FaCamera,
  FaPhotoVideo,
  FaCog,
  FaWrench,
  FaTools,
  FaCogs,
  FaSlidersH,
  FaSyncAlt,
  FaLock,
  FaUnlock,
  FaShoppingCart,
  FaCreditCard,
  FaMoneyBillWave,
  FaPaypal,
  FaCartPlus,
  FaStore,
  FaUser,
  FaUserCircle,
  FaUserAlt,
  FaUsers,
  FaUserPlus,
  FaUserCheck,
  FaChartBar,
  FaChartPie,
  FaChartLine,
  FaTachometerAlt,
  FaTable,
  FaStar,
  FaHeart,
  FaBell,
  FaBookmark,
  FaCalendarAlt,
  FaQuestionCircle,
  FaLightbulb,
  FaRocket,
} from "react-icons/fa";
import {
  MdEmail,
  MdPhone,
  MdLocationOn,
  MdSettings,
  MdDashboard,
  MdAttachFile,
} from "react-icons/md";
import { AiOutlineCloudUpload, AiOutlineCloudDownload } from "react-icons/ai";
import { BsFillPersonFill, BsFillCartFill } from "react-icons/bs";
import { IoMdAnalytics } from "react-icons/io";
import { RiFileUserLine } from "react-icons/ri";
import { GiShoppingBag } from "react-icons/gi";
import { SiGooglemaps } from "react-icons/si";

export const iconsByCategory = [
  {
    category: "🧠 Dev & Code",
    icons: [
      {
        icon: <FaCode size={28} />,
        name: "FaCode",
        importLine: `import { FaCode } from 'react-icons/fa';`,
        example: `<FaCode size={28} />`,
      },
      {
        icon: <FaTerminal size={28} />,
        name: "FaTerminal",
        importLine: `import { FaTerminal } from 'react-icons/fa';`,
        example: `<FaTerminal size={28} />`,
      },
      {
        icon: <FaLaptopCode size={28} />,
        name: "FaLaptopCode",
        importLine: `import { FaLaptopCode } from 'react-icons/fa';`,
        example: `<FaLaptopCode size={28} />`,
      },
      {
        icon: <FaGithub size={28} />,
        name: "FaGithub",
        importLine: `import { FaGithub } from 'react-icons/fa';`,
        example: `<FaGithub size={28} />`,
      },
      {
        icon: <FaGitAlt size={28} />,
        name: "FaGitAlt",
        importLine: `import { FaGitAlt } from 'react-icons/fa';`,
        example: `<FaGitAlt size={28} />`,
      },
      {
        icon: <FaGitlab size={28} />,
        name: "FaGitlab",
        importLine: `import { FaGitlab } from 'react-icons/fa';`,
        example: `<FaGitlab size={28} />`,
      },
      {
        icon: <FaJs size={28} />,
        name: "FaJs",
        importLine: `import { FaJs } from 'react-icons/fa';`,
        example: `<FaJs size={28} />`,
      },
      {
        icon: <FaPython size={28} />,
        name: "FaPython",
        importLine: `import { FaPython } from 'react-icons/fa';`,
        example: `<FaPython size={28} />`,
      },
      {
        icon: <FaJava size={28} />,
        name: "FaJava",
        importLine: `import { FaJava } from 'react-icons/fa';`,
        example: `<FaJava size={28} />`,
      },
      {
        icon: <FaHtml5 size={28} />,
        name: "FaHtml5",
        importLine: `import { FaHtml5 } from 'react-icons/fa';`,
        example: `<FaHtml5 size={28} />`,
      },
      {
        icon: <FaCss3Alt size={28} />,
        name: "FaCss3Alt",
        importLine: `import { FaCss3Alt } from 'react-icons/fa';`,
        example: `<FaCss3Alt size={28} />`,
      },
      {
        icon: <FaReact size={28} />,
        name: "FaReact",
        importLine: `import { FaReact } from 'react-icons/fa';`,
        example: `<FaReact size={28} />`,
      },
      {
        icon: <FaNodeJs size={28} />,
        name: "FaNodeJs",
        importLine: `import { FaNodeJs } from 'react-icons/fa';`,
        example: `<FaNodeJs size={28} />`,
      },
    ],
  },
  {
    category: "🌐 Social Media",
    icons: [
      {
        icon: <FaFacebook size={28} color="#4267B2" />,
        name: "FaFacebook",
        importLine: `import { FaFacebook } from 'react-icons/fa';`,
        example: `<FaFacebook size={28} color="#4267B2" />`,
      },
      {
        icon: <FaTwitter size={28} color="#1DA1F2" />,
        name: "FaTwitter",
        importLine: `import { FaTwitter } from 'react-icons/fa';`,
        example: `<FaTwitter size={28} color="#1DA1F2" />`,
      },
      {
        icon: <FaInstagram size={28} color="#E1306C" />,
        name: "FaInstagram",
        importLine: `import { FaInstagram } from 'react-icons/fa';`,
        example: `<FaInstagram size={28} color="#E1306C" />`,
      },
      {
        icon: <FaLinkedin size={28} color="#0077B5" />,
        name: "FaLinkedin",
        importLine: `import { FaLinkedin } from 'react-icons/fa';`,
        example: `<FaLinkedin size={28} color="#0077B5" />`,
      },
      {
        icon: <FaYoutube size={28} color="#FF0000" />,
        name: "FaYoutube",
        importLine: `import { FaYoutube } from 'react-icons/fa';`,
        example: `<FaYoutube size={28} color="#FF0000" />`,
      },
      {
        icon: <FaReddit size={28} color="#FF4500" />,
        name: "FaReddit",
        importLine: `import { FaReddit } from 'react-icons/fa';`,
        example: `<FaReddit size={28} color="#FF4500" />`,
      },
      {
        icon: <FaWhatsapp size={28} color="#25D366" />,
        name: "FaWhatsapp",
        importLine: `import { FaWhatsapp } from 'react-icons/fa';`,
        example: `<FaWhatsapp size={28} color="#25D366" />`,
      },
      {
        icon: <FaTelegram size={28} color="#0088cc" />,
        name: "FaTelegram",
        importLine: `import { FaTelegram } from 'react-icons/fa';`,
        example: `<FaTelegram size={28} color="#0088cc" />`,
      },
      {
        icon: <FaDiscord size={28} color="#7289da" />,
        name: "FaDiscord",
        importLine: `import { FaDiscord } from 'react-icons/fa';`,
        example: `<FaDiscord size={28} color="#7289da" />`,
      },
      {
        icon: <FaTiktok size={28} color="#000" />,
        name: "FaTiktok",
        importLine: `import { FaTiktok } from 'react-icons/fa';`,
        example: `<FaTiktok size={28} color="#000" />`,
      },
    ],
  },
  {
    category: "📍 Map & Location",
    icons: [
      {
        icon: <FaMapMarkerAlt size={28} color="#d9534f" />,
        name: "FaMapMarkerAlt",
        importLine: `import { FaMapMarkerAlt } from 'react-icons/fa';`,
        example: `<FaMapMarkerAlt size={28} color="#d9534f" />`,
      },
      {
        icon: <FaLocationArrow size={28} />,
        name: "FaLocationArrow",
        importLine: `import { FaLocationArrow } from 'react-icons/fa';`,
        example: `<FaLocationArrow size={28} />`,
      },
      {
        icon: <FaMap size={28} />,
        name: "FaMap",
        importLine: `import { FaMap } from 'react-icons/fa';`,
        example: `<FaMap size={28} />`,
      },
      {
        icon: <FaMapPin size={28} />,
        name: "FaMapPin",
        importLine: `import { FaMapPin } from 'react-icons/fa';`,
        example: `<FaMapPin size={28} />`,
      },
      {
        icon: <FaGlobe size={28} />,
        name: "FaGlobe",
        importLine: `import { FaGlobe } from 'react-icons/fa';`,
        example: `<FaGlobe size={28} />`,
      },
      {
        icon: <FaStreetView size={28} />,
        name: "FaStreetView",
        importLine: `import { FaStreetView } from 'react-icons/fa';`,
        example: `<FaStreetView size={28} />`,
      },
      {
        icon: <MdLocationOn size={28} />,
        name: "MdLocationOn",
        importLine: `import { MdLocationOn } from 'react-icons/md';`,
        example: `<MdLocationOn size={28} />`,
      },
      {
        icon: <SiGooglemaps size={28} color="#4285F4" />,
        name: "SiGooglemaps",
        importLine: `import { SiGooglemaps } from 'react-icons/si';`,
        example: `<SiGooglemaps size={28} color="#4285F4" />`,
      },
    ],
  },
  {
    category: "🧭 Navigation & UI",
    icons: [
      {
        icon: <FaCompass size={28} />,
        name: "FaCompass",
        importLine: `import { FaCompass } from 'react-icons/fa';`,
        example: `<FaCompass size={28} />`,
      },
      {
        icon: <FaArrowLeft size={28} />,
        name: "FaArrowLeft",
        importLine: `import { FaArrowLeft } from 'react-icons/fa';`,
        example: `<FaArrowLeft size={28} />`,
      },
      {
        icon: <FaArrowRight size={28} />,
        name: "FaArrowRight",
        importLine: `import { FaArrowRight } from 'react-icons/fa';`,
        example: `<FaArrowRight size={28} />`,
      },
      {
        icon: <FaArrowUp size={28} />,
        name: "FaArrowUp",
        importLine: `import { FaArrowUp } from 'react-icons/fa';`,
        example: `<FaArrowUp size={28} />`,
      },
      {
        icon: <FaArrowDown size={28} />,
        name: "FaArrowDown",
        importLine: `import { FaArrowDown } from 'react-icons/fa';`,
        example: `<FaArrowDown size={28} />`,
      },
      {
        icon: <FaHome size={28} />,
        name: "FaHome",
        importLine: `import { FaHome } from 'react-icons/fa';`,
        example: `<FaHome size={28} />`,
      },
      {
        icon: <FaBars size={28} />,
        name: "FaBars",
        importLine: `import { FaBars } from 'react-icons/fa';`,
        example: `<FaBars size={28} />`,
      },
      {
        icon: <FaTimes size={28} />,
        name: "FaTimes",
        importLine: `import { FaTimes } from 'react-icons/fa';`,
        example: `<FaTimes size={28} />`,
      },
      {
        icon: <FaChevronLeft size={28} />,
        name: "FaChevronLeft",
        importLine: `import { FaChevronLeft } from 'react-icons/fa';`,
        example: `<FaChevronLeft size={28} />`,
      },
      {
        icon: <FaChevronRight size={28} />,
        name: "FaChevronRight",
        importLine: `import { FaChevronRight } from 'react-icons/fa';`,
        example: `<FaChevronRight size={28} />`,
      },
    ],
  },
  {
    category: "📞 Communication",
    icons: [
      {
        icon: <FaPhone size={28} />,
        name: "FaPhone",
        importLine: `import { FaPhone } from 'react-icons/fa';`,
        example: `<FaPhone size={28} />`,
      },
      {
        icon: <FaPhoneAlt size={28} />,
        name: "FaPhoneAlt",
        importLine: `import { FaPhoneAlt } from 'react-icons/fa';`,
        example: `<FaPhoneAlt size={28} />`,
      },
      {
        icon: <FaEnvelope size={28} />,
        name: "FaEnvelope",
        importLine: `import { FaEnvelope } from 'react-icons/fa';`,
        example: `<FaEnvelope size={28} />`,
      },
      {
        icon: <FaSms size={28} />,
        name: "FaSms",
        importLine: `import { FaSms } from 'react-icons/fa';`,
        example: `<FaSms size={28} />`,
      },
      {
        icon: <FaCommentDots size={28} />,
        name: "FaCommentDots",
        importLine: `import { FaCommentDots } from 'react-icons/fa';`,
        example: `<FaCommentDots size={28} />`,
      },
      {
        icon: <FaMailBulk size={28} />,
        name: "FaMailBulk",
        importLine: `import { FaMailBulk } from 'react-icons/fa';`,
        example: `<FaMailBulk size={28} />`,
      },
      {
        icon: <MdEmail size={28} />,
        name: "MdEmail",
        importLine: `import { MdEmail } from 'react-icons/md';`,
        example: `<MdEmail size={28} />`,
      },
      {
        icon: <MdPhone size={28} />,
        name: "MdPhone",
        importLine: `import { MdPhone } from 'react-icons/md';`,
        example: `<MdPhone size={28} />`,
      },
    ],
  },
  {
    category: "📁 File & Media",
    icons: [
      {
        icon: <FaFile size={28} />,
        name: "FaFile",
        importLine: `import { FaFile } from 'react-icons/fa';`,
        example: `<FaFile size={28} />`,
      },
      {
        icon: <FaFileAlt size={28} />,
        name: "FaFileAlt",
        importLine: `import { FaFileAlt } from 'react-icons/fa';`,
        example: `<FaFileAlt size={28} />`,
      },
      {
        icon: <FaFilePdf size={28} color="#e74c3c" />,
        name: "FaFilePdf",
        importLine: `import { FaFilePdf } from 'react-icons/fa';`,
        example: `<FaFilePdf size={28} color="#e74c3c" />`,
      },
      {
        icon: <FaFileImage size={28} />,
        name: "FaFileImage",
        importLine: `import { FaFileImage } from 'react-icons/fa';`,
        example: `<FaFileImage size={28} />`,
      },
      {
        icon: <FaFileVideo size={28} />,
        name: "FaFileVideo",
        importLine: `import { FaFileVideo } from 'react-icons/fa';`,
        example: `<FaFileVideo size={28} />`,
      },
      {
        icon: <FaFolder size={28} />,
        name: "FaFolder",
        importLine: `import { FaFolder } from 'react-icons/fa';`,
        example: `<FaFolder size={28} />`,
      },
      {
        icon: <FaDownload size={28} />,
        name: "FaDownload",
        importLine: `import { FaDownload } from 'react-icons/fa';`,
        example: `<FaDownload size={28} />`,
      },
      {
        icon: <FaUpload size={28} />,
        name: "FaUpload",
        importLine: `import { FaUpload } from 'react-icons/fa';`,
        example: `<FaUpload size={28} />`,
      },
      {
        icon: <FaCamera size={28} />,
        name: "FaCamera",
        importLine: `import { FaCamera } from 'react-icons/fa';`,
        example: `<FaCamera size={28} />`,
      },
      {
        icon: <FaPhotoVideo size={28} />,
        name: "FaPhotoVideo",
        importLine: `import { FaPhotoVideo } from 'react-icons/fa';`,
        example: `<FaPhotoVideo size={28} />`,
      },
      {
        icon: <MdAttachFile size={28} />,
        name: "MdAttachFile",
        importLine: `import { MdAttachFile } from 'react-icons/md';`,
        example: `<MdAttachFile size={28} />`,
      },
      {
        icon: <AiOutlineCloudUpload size={28} />,
        name: "AiOutlineCloudUpload",
        importLine: `import { AiOutlineCloudUpload } from 'react-icons/ai';`,
        example: `<AiOutlineCloudUpload size={28} />`,
      },
      {
        icon: <AiOutlineCloudDownload size={28} />,
        name: "AiOutlineCloudDownload",
        importLine: `import { AiOutlineCloudDownload } from 'react-icons/ai';`,
        example: `<AiOutlineCloudDownload size={28} />`,
      },
    ],
  },
  {
    category: "⚙️ Settings & Tools",
    icons: [
      {
        icon: <FaCog size={28} />,
        name: "FaCog",
        importLine: `import { FaCog } from 'react-icons/fa';`,
        example: `<FaCog size={28} />`,
      },
      {
        icon: <FaWrench size={28} />,
        name: "FaWrench",
        importLine: `import { FaWrench } from 'react-icons/fa';`,
        example: `<FaWrench size={28} />`,
      },
      {
        icon: <FaTools size={28} />,
        name: "FaTools",
        importLine: `import { FaTools } from 'react-icons/fa';`,
        example: `<FaTools size={28} />`,
      },
      {
        icon: <FaCogs size={28} />,
        name: "FaCogs",
        importLine: `import { FaCogs } from 'react-icons/fa';`,
        example: `<FaCogs size={28} />`,
      },
      {
        icon: <FaSlidersH size={28} />,
        name: "FaSlidersH",
        importLine: `import { FaSlidersH } from 'react-icons/fa';`,
        example: `<FaSlidersH size={28} />`,
      },
      {
        icon: <FaSyncAlt size={28} />,
        name: "FaSyncAlt",
        importLine: `import { FaSyncAlt } from 'react-icons/fa';`,
        example: `<FaSyncAlt size={28} />`,
      },
      {
        icon: <MdSettings size={28} />,
        name: "MdSettings",
        importLine: `import { MdSettings } from 'react-icons/md';`,
        example: `<MdSettings size={28} />`,
      },
    ],
  },
  {
    category: "🛒 E-commerce",
    icons: [
      {
        icon: <FaShoppingCart size={28} />,
        name: "FaShoppingCart",
        importLine: `import { FaShoppingCart } from 'react-icons/fa';`,
        example: `<FaShoppingCart size={28} />`,
      },
      {
        icon: <FaCreditCard size={28} />,
        name: "FaCreditCard",
        importLine: `import { FaCreditCard } from 'react-icons/fa';`,
        example: `<FaCreditCard size={28} />`,
      },
      {
        icon: <FaMoneyBillWave size={28} />,
        name: "FaMoneyBillWave",
        importLine: `import { FaMoneyBillWave } from 'react-icons/fa';`,
        example: `<FaMoneyBillWave size={28} />`,
      },
      {
        icon: <FaPaypal size={28} />,
        name: "FaPaypal",
        importLine: `import { FaPaypal } from 'react-icons/fa';`,
        example: `<FaPaypal size={28} />`,
      },
      {
        icon: <FaCartPlus size={28} />,
        name: "FaCartPlus",
        importLine: `import { FaCartPlus } from 'react-icons/fa';`,
        example: `<FaCartPlus size={28} />`,
      },
      {
        icon: <FaStore size={28} />,
        name: "FaStore",
        importLine: `import { FaStore } from 'react-icons/fa';`,
        example: `<FaStore size={28} />`,
      },
      {
        icon: <BsFillCartFill size={28} />,
        name: "BsFillCartFill",
        importLine: `import { BsFillCartFill } from 'react-icons/bs';`,
        example: `<BsFillCartFill size={28} />`,
      },
      {
        icon: <GiShoppingBag size={28} />,
        name: "GiShoppingBag",
        importLine: `import { GiShoppingBag } from 'react-icons/gi';`,
        example: `<GiShoppingBag size={28} />`,
      },
    ],
  },
  {
    category: "👤 User & Account",
    icons: [
      {
        icon: <FaUser size={28} />,
        name: "FaUser",
        importLine: `import { FaUser } from 'react-icons/fa';`,
        example: `<FaUser size={28} />`,
      },
      {
        icon: <FaUserCircle size={28} />,
        name: "FaUserCircle",
        importLine: `import { FaUserCircle } from 'react-icons/fa';`,
        example: `<FaUserCircle size={28} />`,
      },
      {
        icon: <FaUserAlt size={28} />,
        name: "FaUserAlt",
        importLine: `import { FaUserAlt } from 'react-icons/fa';`,
        example: `<FaUserAlt size={28} />`,
      },
      {
        icon: <FaUsers size={28} />,
        name: "FaUsers",
        importLine: `import { FaUsers } from 'react-icons/fa';`,
        example: `<FaUsers size={28} />`,
      },
      {
        icon: <FaUserPlus size={28} />,
        name: "FaUserPlus",
        importLine: `import { FaUserPlus } from 'react-icons/fa';`,
        example: `<FaUserPlus size={28} />`,
      },
      {
        icon: <FaUserCheck size={28} />,
        name: "FaUserCheck",
        importLine: `import { FaUserCheck } from 'react-icons/fa';`,
        example: `<FaUserCheck size={28} />`,
      },
      {
        icon: <BsFillPersonFill size={28} />,
        name: "BsFillPersonFill",
        importLine: `import { BsFillPersonFill } from 'react-icons/bs';`,
        example: `<BsFillPersonFill size={28} />`,
      },
      {
        icon: <RiFileUserLine size={28} />,
        name: "RiFileUserLine",
        importLine: `import { RiFileUserLine } from 'react-icons/ri';`,
        example: `<RiFileUserLine size={28} />`,
      },
    ],
  },
  {
    category: "📊 Analytics & Dashboard",
    icons: [
      {
        icon: <FaChartBar size={28} />,
        name: "FaChartBar",
        importLine: `import { FaChartBar } from 'react-icons/fa';`,
        example: `<FaChartBar size={28} />`,
      },
      {
        icon: <FaChartPie size={28} />,
        name: "FaChartPie",
        importLine: `import { FaChartPie } from 'react-icons/fa';`,
        example: `<FaChartPie size={28} />`,
      },
      {
        icon: <FaChartLine size={28} />,
        name: "FaChartLine",
        importLine: `import { FaChartLine } from 'react-icons/fa';`,
        example: `<FaChartLine size={28} />`,
      },
      {
        icon: <FaTachometerAlt size={28} />,
        name: "FaTachometerAlt",
        importLine: `import { FaTachometerAlt } from 'react-icons/fa';`,
        example: `<FaTachometerAlt size={28} />`,
      },
      {
        icon: <FaTable size={28} />,
        name: "FaTable",
        importLine: `import { FaTable } from 'react-icons/fa';`,
        example: `<FaTable size={28} />`,
      },
      {
        icon: <MdDashboard size={28} />,
        name: "MdDashboard",
        importLine: `import { MdDashboard } from 'react-icons/md';`,
        example: `<MdDashboard size={28} />`,
      },
      {
        icon: <IoMdAnalytics size={28} />,
        name: "IoMdAnalytics",
        importLine: `import { IoMdAnalytics } from 'react-icons/io';`,
        example: `<IoMdAnalytics size={28} />`,
      },
    ],
  },
  {
    category: "⭐ Miscellaneous",
    icons: [
      {
        icon: <FaStar size={28} color="#FFD700" />,
        name: "FaStar",
        importLine: `import { FaStar } from 'react-icons/fa';`,
        example: `<FaStar size={28} color="#FFD700" />`,
      },
      {
        icon: <FaHeart size={28} color="#e25555" />,
        name: "FaHeart",
        importLine: `import { FaHeart } from 'react-icons/fa';`,
        example: `<FaHeart size={28} color="#e25555" />`,
      },
      {
        icon: <FaBell size={28} />,
        name: "FaBell",
        importLine: `import { FaBell } from 'react-icons/fa';`,
        example: `<FaBell size={28} />`,
      },
      {
        icon: <FaBookmark size={28} />,
        name: "FaBookmark",
        importLine: `import { FaBookmark } from 'react-icons/fa';`,
        example: `<FaBookmark size={28} />`,
      },
      {
        icon: <FaCalendarAlt size={28} />,
        name: "FaCalendarAlt",
        importLine: `import { FaCalendarAlt } from 'react-icons/fa';`,
        example: `<FaCalendarAlt size={28} />`,
      },
      {
        icon: <FaQuestionCircle size={28} />,
        name: "FaQuestionCircle",
        importLine: `import { FaQuestionCircle } from 'react-icons/fa';`,
        example: `<FaQuestionCircle size={28} />`,
      },
      {
        icon: <FaLightbulb size={28} />,
        name: "FaLightbulb",
        importLine: `import { FaLightbulb } from 'react-icons/fa';`,
        example: `<FaLightbulb size={28} />`,
      },
      {
        icon: <FaRocket size={28} />,
        name: "FaRocket",
        importLine: `import { FaRocket } from 'react-icons/fa';`,
        example: `<FaRocket size={28} />`,
      },
    ],
  },
];
